# Makefile.Vx
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


SRCS.c = $(wildcard ../*.c)
tmpobjs = $(SRCS.c:.c=.o)
LIBOBJS = $(notdir $(tmpobjs))

LIBNAME = slaLib

#Note that the command line that builds the
#library $(LIBNAME) may be HUGE (>3kB)
#
include $(TOP)/config/RULES.Vx
#----------------------------------------
#  ADD RULES AFTER THIS LINE
